### PR TITLE
Change how to display speakers data

### PR DESCRIPTION
**Pull request by Danble**
#### Relevant Issue
#157 
#### Summarize what changed in this PR (for developers)
I changed many things in this PR in order to allow to show the birthplace of the speaker in the EditAudio and the SelectSpeaker modals. I also allow to display this modal not only for managers but for anyone: hiding the editable part (the modal footer). In order to allow both functionalities: show modal and to listen the audio without popup anything, I changed the longpress action for a double click event and I created a component to handle the co-existence of both capabilities without overlapping (please feel free to move that component to another folder if needed). 

#### Summarize changes in this PR (for public-facing changelog)
Allow speaker modal for every user and show speaker birthplace.
image

#### How can the changes be tested? Please also provide applicable links using preview deployments once they are available (will require editing this message once the preview deployment is ready).
Please try and test with different role levels:
http://localhost:3041/bezhta/entries/list
https://living-dictionaries-cgutcl1wb-livingtongues.vercel.app/bezhta/entries/list

<a href="https://gitpod.io/#https://github.com/livingtongues/living-dictionaries/pull/167"></a>

### CODE REVIEW

**Comment by Danble** [comment]
@jacob-8 Please review carefully this PR. The main thing in this case is the `packages/scripts/algolia/prepareDataForIndex.ts`.
But I did many different changes, please look at them.

**Comment by AnnaLuisaD** [comment]
The reason for this change is because we've had requests from users who want to see the name of the speaker when they are listening to the audio, and they also want to see the birthplace of the speaker. I also feel that seeing the waveform is a powerful feature, and that everyone should have access to seeing the audio waveform while listening to the sound. but of course we don't regular users to be able to delete or change the file, etc.

**Comment by AnnaLuisaD** [comment]
I am also open to hearing any of Jacob's reasons for not having a pop-up audio module. I think we need to have the pop-up, even if it adds an extra step to the user experience. I would argue that having the pop-up being visible to everyone allows the person to get more information about the audio they are hearing

**Comment by jacob-8** [comment]
@AnnaLuisaD I like this idea, just haven't had time to think about it much yet.

**Comment by jacob-8** [comment]
@AnnaLuisaD to update - will look at this after #274 is done.

**Comment by jacob-8** [comment]
Closing this for now as it should be several different pull requests and things are too intertwined. I'd like to take this in smaller chunks further down the road so I've added it to our roadmap as a draft note: "Show audio popup with speaker name, birthplace, and waveform for all listeners not just editors"

**Pull request closed without merging**
