### PR TITLE
Update to latest Sveltefirets

### PR DESCRIPTION
**Pull request by jacobbowdoin**

### CODE REVIEW

**Comment by Danble** [comment]
On https://living-dictionaries-iaw599n1r-livingtongues.vercel.app/ I found these problems. I think they are related with the entries and entry pages
image
image
I'm able to create a dictionary though

**Comment by Danble** [comment]
On localhost I'm getting this errors:
image
image
I'm did a `npm i` before anything. I'm using node v16.13.0 and npm 8.1.0

**Comment by jacobbowdoin** [comment]
@Danble those page freezing issues were due to a bad "optimization" I made to the Doc and Collection sveltefirets components that caused them to infinite loop. It's fixed now, can you test again, please?

**Review by Danble — APPROVED** [review]
Great, @jacobbowdoin! I watched your video, thank you for taking the time to teach me.
It looks nicer and it works perfect both in local & in vercel URL. 
I tried to test almost everything and on every test it ran smoothly!

**Pull request merged**
