### PR TITLE
New plural form field

### PR DESCRIPTION
**Pull request by Danble**
#### Relevant Issue
#186 
#### Summarize what changed in this PR (for developers)
I added the new "Plural form" field on the entry view, table view, also added as a new i18n text, import files and in the export csv file
#### Summarize changes in this PR (for public-facing changelog)
image
image

#### How can the changes be tested? Please also provide applicable links using preview deployments once they are available (will require editing this message once the preview deployment is ready).
https://living-dictionaries-cp5d5ozau-livingtongues.vercel.app/apatani/entries/table
https://living-dictionaries-cp5d5ozau-livingtongues.vercel.app/apatani/entry/q1oPosC9uuQbTzwoAjZc (as admin)
https://living-dictionaries-cp5d5ozau-livingtongues.vercel.app/apatani/export

### CODE REVIEW

**Comment by Danble** [comment]
@AnnaLuisaD I only want to: 

1. add a new file in the documentation folder in order to know what else to do if we need to add a new entry field in the future.
2. know if we need a filter or filters for this new field _has plural form_ or the filters of any plural form the users would add

**Comment by AnnaLuisaD** [comment]
@Danble yes, great question about needing a filter. my instinct says they might want this filter for Bantu languages in Africa. so I think we could go ahead and add a filter.

**Comment by Danble** [comment]
So only a _has plural form_ filter?

**Comment by jacob-8** [comment]
- [x] I updated the translation spreadsheet from plf to pl already. 
- [ ] @Danble update the settings in Algolia to take advantage of `hasPluralForm` in the same manner as `hasPartOfSpeech`.
- [ ] Before merging, I want to redeploy the Algolia functions with the updated code. Please don't merge until I do.
- [ ] @Danble, can you confirm that new field has been added to import template?

**Comment by Danble** [comment]
Hi @jacob-8 I have added the facet based in the parts of speech a you suggested in algolia dev environment. 
image
I also added the ToggleRefinement component for hasPluralForm, however I can't see the filter neither in my localhost nor in the vercel link: https://living-dictionaries-eayyl3q3e-livingtongues.vercel.app/test-004/entries/list
Am I missing something or does it only work on prod?
Anna added the colum for this plural form. Is that what you mean in the last checkpoint? 
image
I also added the necessary code in `packages\scripts\import\convertJsonRowToEntryFormat.ts`

**Pull request merged**
